### ISSUE TITLE
 RangeError: Invalid array length  

### ISSUE THREAD

**Issue by sukeerthimogallapalli** [gwjjeff/cryptojs#16]

**Comment by sukeerthimogallapalli** [comment]
Hi

i am trying to decrypt private key but i am getting this error 

/home/ahex/Desktop/tokenize.node/node_modules/crypto-js/core.js:272
	            words.length = Math.ceil(sigBytes / 4);
	                         ^

RangeError: Invalid array length
    at WordArray.init.clamp (/home/ahex/Desktop/tokenize.node/node_modules/crypto-js/core.js:272:27)
    at WordArray.init.concat (/home/ahex/Desktop/tokenize.node/node_modules/crypto-js/core.js:237:19)


My code :

var CryptoJS = require('crypto-js')
var cryptoSecret = '*************************'
var SenderPrivateKey = new bitcore.PrivateKey('testnet');
console.log(SenderPrivateKey)
//<PrivateKey: 8c6251ff3ee21e54bc15485c2ea8f7491501a7a684ecc08dfd95a993f048e06e, network: //testnet>

var a = CryptoJS.AES.encrypt(SenderPrivateKey, cryptoSecret)

**Comment by dmytro-kupriianov** [comment]
The same problem

**Comment by Synat** [comment]
The same problem

**Comment by michaelpeterlee** [comment]
This error is triggered when you pass an object, rather than a string.

**Comment by gocreating** [comment]
It's 2020 and I still get the same problem

**Comment by JuanxCursed** [comment]
Same problem here, even passing a simple string

**Comment by pussio** [comment]
It should works after u make it a string, try to do `${your_variable}` just to make sure its a string

**Comment by yquintana** [comment]
> Este error se activa cuando pasa un objeto, en lugar de una cadena.

it's true..

**Comment by nezihsunman** [comment]
When the same thing happened to me I "stringify"

```
CryptoJS.AES.encrypt( JSON.stringify({
    username: username,
    text: text,
    createdAt: new Date().getTime()
  }), '123456').toString();
```

**Comment by midhun1993** [comment]
For me this issue occurred due to the type `number`.

So I did like this:
```
function transformToSafePayload(payload) {
  if (typeof payload == 'object') {
    return JSON.stringify(payload);
  }
  if (typeof payload != 'string') {
    return payload.toString();
  }
  return payload;
}


CryptoJS.AES.encrypt(transformToSafePayload({
    username: username,
    text: text,
    createdAt: new Date().getTime()
  }), '123456').toString();
```

**Comment by mcaceresDev** [comment]
exacto! mi problema fue por pasar un parametro de tipo numero. Primero tuve que pasarlo a string para encriptarlo.
